### ISSUE TITLE
Refactor transport module to use proper naming convention for transactionId in signature

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1041]
Currently in `/signatures` endpoint, we are accepting following object. 

```
  Signature:
    type: object
    required:
      - transactionId
      - publicKey
      - signature
    properties:
      transactionId:
        type: string
        format: id
        example: "222675625422353767"
        minLength: 1
        maxLength: 20
      publicKey:
        type: string
        format: publicKey
        example: 2ca9a7143fc721fdc540fef893b27e8d648d2288efa61e56264edf01a2c23079
      signature:
        type: string
        format: signature
        example: 2821d93a742c4edf5fd960efad41a4def7bf0fd0f7c09869aed524f6f52bf9c97a617095e2c712bd28b4279078a29509b339ac55187854006591aa759784c205
```

Underlying modules are using `transaction` attribute as `transactionId`. We need to refactor the underlying module to use proper naming convention for variables and parameter names. So the code should be more readable and stay consistent.
